---
title: "CodeBook Tidy Data for HAR Dataset - v1"
author: "Valerie QUINIOU"
date: "10/9/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### CodeBook - Getting and Cleaning Data - Week 4 - Assignment
## I - Context
The aim of the project is to generate a tidy dataset from the Human Acticity Recognition (HAR) Smartphone datasets. The HAR dataset is composed of several time series datasets built on recording daily living activities performed by 30 volunteers wearing a waist-mounted Smartphone. The measures were "captured" from the Smartphone built-in sensors. 
The HAR dataset can be downloaded at https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 
More information on the HAR study can be found at http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

## II - Explanations on the HAR project measurements
Extract from the HAR "features_info.txt" :
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

        tBodyAcc-XYZ
        tGravityAcc-XYZ
        tBodyAccJerk-XYZ
        tBodyGyro-XYZ
        tBodyGyroJerk-XYZ
        tBodyAccMag
        tGravityAccMag
        tBodyAccJerkMag
        tBodyGyroMag
        tBodyGyroJerkMag
        fBodyAcc-XYZ
        fBodyAccJerk-XYZ
        fBodyGyro-XYZ
        fBodyAccMag
        fBodyAccJerkMag
        fBodyGyroMag
        fBodyGyroJerkMag

The work focuses on the variables for mean and standard deviation values in the HAR dataset.
The mean ("mean"" in the variable name) and standard variation ("std"" in the variable name) variables used were : 

        [1] "tBodyAcc-mean()-X"               "tBodyAcc-mean()-Y"               "tBodyAcc-mean()-Z"               "tBodyAcc-std()-X"               
        [5] "tBodyAcc-std()-Y"                "tBodyAcc-std()-Z"                "tGravityAcc-mean()-X"            "tGravityAcc-mean()-Y"           
        [9] "tGravityAcc-mean()-Z"            "tGravityAcc-std()-X"             "tGravityAcc-std()-Y"             "tGravityAcc-std()-Z"            
        [13] "tBodyAccJerk-mean()-X"           "tBodyAccJerk-mean()-Y"           "tBodyAccJerk-mean()-Z"           "tBodyAccJerk-std()-X"           
        [17] "tBodyAccJerk-std()-Y"            "tBodyAccJerk-std()-Z"            "tBodyGyro-mean()-X"              "tBodyGyro-mean()-Y"             
        [21] "tBodyGyro-mean()-Z"              "tBodyGyro-std()-X"               "tBodyGyro-std()-Y"               "tBodyGyro-std()-Z"              
        [25] "tBodyGyroJerk-mean()-X"          "tBodyGyroJerk-mean()-Y"          "tBodyGyroJerk-mean()-Z"          "tBodyGyroJerk-std()-X"          
        [29] "tBodyGyroJerk-std()-Y"           "tBodyGyroJerk-std()-Z"           "tBodyAccMag-mean()"              "tBodyAccMag-std()"              
        [33] "tGravityAccMag-mean()"           "tGravityAccMag-std()"            "tBodyAccJerkMag-mean()"          "tBodyAccJerkMag-std()"          
        [37] "tBodyGyroMag-mean()"             "tBodyGyroMag-std()"              "tBodyGyroJerkMag-mean()"         "tBodyGyroJerkMag-std()"         
        [41] "fBodyAcc-mean()-X"               "fBodyAcc-mean()-Y"               "fBodyAcc-mean()-Z"               "fBodyAcc-std()-X"               
        [45] "fBodyAcc-std()-Y"                "fBodyAcc-std()-Z"                "fBodyAcc-meanFreq()-X"           "fBodyAcc-meanFreq()-Y"          
        [49] "fBodyAcc-meanFreq()-Z"           "fBodyAccJerk-mean()-X"           "fBodyAccJerk-mean()-Y"           "fBodyAccJerk-mean()-Z"          
        [53] "fBodyAccJerk-std()-X"            "fBodyAccJerk-std()-Y"            "fBodyAccJerk-std()-Z"            "fBodyAccJerk-meanFreq()-X"      
        [57] "fBodyAccJerk-meanFreq()-Y"       "fBodyAccJerk-meanFreq()-Z"       "fBodyGyro-mean()-X"              "fBodyGyro-mean()-Y"             
        [61] "fBodyGyro-mean()-Z"              "fBodyGyro-std()-X"               "fBodyGyro-std()-Y"               "fBodyGyro-std()-Z"              
        [65] "fBodyGyro-meanFreq()-X"          "fBodyGyro-meanFreq()-Y"          "fBodyGyro-meanFreq()-Z"          "fBodyAccMag-mean()"             
        [69] "fBodyAccMag-std()"               "fBodyAccMag-meanFreq()"          "fBodyBodyAccJerkMag-mean()"      "fBodyBodyAccJerkMag-std()"      
        [73] "fBodyBodyAccJerkMag-meanFreq()"  "fBodyBodyGyroMag-mean()"         "fBodyBodyGyroMag-std()"          "fBodyBodyGyroMag-meanFreq()"    
        [77] "fBodyBodyGyroJerkMag-mean()"     "fBodyBodyGyroJerkMag-std()"      "fBodyBodyGyroJerkMag-meanFreq()" "activity"                       

## III - Dataset management
In order to achieve tidying the HAR dataset, it is necessary to perform several tasks : join the test and train data sets, use descriptive acivity names to name the activities, label the data set with descriptive variable names, and in the end, generate an independant tidy dataset with the average of each variable for each activity and each subject.

## 1 - Merging the HAR dataset
The HAR dataset is split into 2 parts : test and train as follows : 
test : 
- subject_test.txt
- X_test.txt
- y_test.txt

train : 
- subject_train.txt
- X_train.txt
- y_train.txt

We also use the activity_labels.txt and the features.txt files, which are commmon for test and train.

First thing to do : load the needed libraries : data.table and plyr

### 1.1 - Test dataset :
#### 1.1.1 Read the data
Loading all data is done using the fread() function.

#### 1.1.2 Add the column names
Adding the names of the columns, based on the HAR data set "features.txt" file, is done using the colnames() function. 

#### 1.1.3 Add the activities and subjects values to the dataset
Adding the values from the Y_test.txt file to the dataframe is done using the operator ":="

### 1.2 - Train dataset : 
Repeat the same tasks (1.1.1, 1.1.2, 1.1.3) as the ones done for test.

### 1.3 - join test and train
As the structure of the objects for test and train is exactly the same in terms of variables, the task to be done is to add the rows of the one to the other.
This is done using the rbind() funtion.

## 2 - Extract only the variables of mean and standard deviation
This is done by extracting the values from the dataframe where the column names contains "mean" or "std". In order to find the values, the grep() function is used.
I also look for the "activity" and "user" character string, as I also want to get the values for these variables and have one dataframe containing mean, standard deviation, activity and user variables, as so far, there are required for the next steps.

## 3 - rename the activities in the dataset using descriptive acitivity names
The descriptive activity names are provided in the activity_labels.txt file.
First the data from this file is loaded into R.
Then renaming the values in the dataset is done with the match() function. There is a common key between the dataframe and the activity_labels : the ID.
The ID is a number, from 1 to 6. In the activity_labels, we have the corresponding activity to the ID, for instance 1 = WALKING, 2 = WALKING_UPSTAIRS....
We check if the activity ID in the dataframe exists in the activity_labels, and if this is the case, we extract the corresponding value and write it down in the activity variable of the dataframe.

## 4 - Name all variables with descriptive names
This operation is done by using the gsub() function on the dataframe variable names. 
- All unwanted characters are removed : "(", ")", "-"
- Several character strings are transformed to be more explicit (see the run_analysis.R script for the list of the character strings).

## 5 - Create a second tidy dataset with the average of each variables for each activity and each subject
### 5.1 - Calculate the mean for each variable by activity and by subject
This is done using the aggregate() function. "." is used to be linked to "activity"" AND "user"" variables. "." here means all variables from the dataframe.

### 5.2 - Generate the .txt file
This is done using the write.table() function. The seperator used is tab " ", and we also write the variable names with header = TRUE.

The result is a .txt file : tidyData.txt

## IV - The new tidy dataset
##### The resulting data set is of class data.table and data.frame. It contains 180 obs. and 81 variables : 

          Activity                                                      : chr  "LAYING" "SITTING" "STANDING" "WALKING" ... 
#####  This is the daily living activities performed by the volunteers during the test
          User                                                          : int  1 1 1 1 1 1 2 2 2 2 ... 
#####  This represents the ID of each volunteer involved in the test. 30 volunteers contributed, so the ID goes from 1 to 30.

##### The following variables are mean calculation for each measurement/variables:  
          TimeBodyAccelerometerMeanXdirection                           : num  0.222 0.261 0.279 0.277 0.289 ...
          TimeBodyAccelerometerMeanYdirection                           : num  -0.04051 -0.00131 -0.01614 -0.01738 -0.00992 ...
          TimeBodyAccelerometerMeanZdirection                           : num  -0.113 -0.105 -0.111 -0.111 -0.108 ...
          TimeBodyAccelerometerStandardDeviationXdirection              : num  -0.928 -0.977 -0.996 -0.284 0.03 ...
          TimeBodyAccelerometerStandardDeviationYdirection              : num  -0.8368 -0.9226 -0.9732 0.1145 -0.0319 ...
          TimeBodyAccelerometerStandardDeviationZdirection              : num  -0.826 -0.94 -0.98 -0.26 -0.23 ...
          TimeGravityAccelerometerMeanXdirection                        : num  -0.249 0.832 0.943 0.935 0.932 ...
          TimeGravityAccelerometerMeanYdirection                        : num  0.706 0.204 -0.273 -0.282 -0.267 ...
          TimeGravityAccelerometerMeanZdirection                        : num  0.4458 0.332 0.0135 -0.0681 -0.0621 ...
          TimeGravityAccelerometerStandardDeviationXdirection           : num  -0.897 -0.968 -0.994 -0.977 -0.951 ...
          TimeGravityAccelerometerStandardDeviationYdirection           : num  -0.908 -0.936 -0.981 -0.971 -0.937 ...
          TimeGravityAccelerometerStandardDeviationZdirection           : num  -0.852 -0.949 -0.976 -0.948 -0.896 ...
          TimeBodyAccelerometerJerkMeanXdirection                       : num  0.0811 0.0775 0.0754 0.074 0.0542 ...
          TimeBodyAccelerometerJerkMeanYdirection                       : num  0.003838 -0.000619 0.007976 0.028272 0.02965 ...
          TimeBodyAccelerometerJerkMeanZdirection                       : num  0.01083 -0.00337 -0.00369 -0.00417 -0.01097 ...
          TimeBodyAccelerometerJerkStandardDeviationXdirection          : num  -0.9585 -0.9864 -0.9946 -0.1136 -0.0123 ...
          TimeBodyAccelerometerJerkStandardDeviationYdirection          : num  -0.924 -0.981 -0.986 0.067 -0.102 ...
          TimeBodyAccelerometerJerkStandardDeviationZdirection          : num  -0.955 -0.988 -0.992 -0.503 -0.346 ...
          TimeBodyGyroscopeMeanXdirection                               : num  -0.0166 -0.0454 -0.024 -0.0418 -0.0351 ...
          TimeBodyGyroscopeMeanYdirection                               : num  -0.0645 -0.0919 -0.0594 -0.0695 -0.0909 ...
          TimeBodyGyroscopeMeanZdirection                               : num  0.1487 0.0629 0.0748 0.0849 0.0901 ...
          TimeBodyGyroscopeStandardDeviationXdirection                  : num  -0.874 -0.977 -0.987 -0.474 -0.458 ...
          TimeBodyGyroscopeStandardDeviationYdirection                  : num  -0.9511 -0.9665 -0.9877 -0.0546 -0.1263 ...
          TimeBodyGyroscopeStandardDeviationZdirection                  : num  -0.908 -0.941 -0.981 -0.344 -0.125 ...
          TimeBodyGyroscopeJerkMeanXdirection                           : num  -0.1073 -0.0937 -0.0996 -0.09 -0.074 ...
          TimeBodyGyroscopeJerkMeanYdirection                           : num  -0.0415 -0.0402 -0.0441 -0.0398 -0.044 ...
          TimeBodyGyroscopeJerkMeanZdirection                           : num  -0.0741 -0.0467 -0.049 -0.0461 -0.027 ...
          TimeBodyGyroscopeJerkStandardDeviationXdirection              : num  -0.919 -0.992 -0.993 -0.207 -0.487 ...
          TimeBodyGyroscopeJerkStandardDeviationYdirection              : num  -0.968 -0.99 -0.995 -0.304 -0.239 ...
          TimeBodyGyroscopeJerkStandardDeviationZdirection              : num  -0.958 -0.988 -0.992 -0.404 -0.269 ...
          TimeBodyAccelerometerMagnitudeMean                            : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
          TimeBodyAccelerometerMagnitudeStandardDeviation               : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
          TimeGravityAccelerometerMagnitudeMean                         : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
          TimeGravityAccelerometerMagnitudeStandardDeviation            : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
          TimeBodyAccelerometerJerkMagnitudeMean                        : num  -0.9544 -0.9874 -0.9924 -0.1414 -0.0894 ...
          TimeBodyAccelerometerJerkMagnitudeStandardDeviation           : num  -0.9282 -0.9841 -0.9931 -0.0745 -0.0258 ...
          TimeBodyGyroscopeMagnitudeMean                                : num  -0.8748 -0.9309 -0.9765 -0.161 -0.0757 ...
          TimeBodyGyroscopeMagnitudeStandardDeviation                   : num  -0.819 -0.935 -0.979 -0.187 -0.226 ...
          TimeBodyGyroscopeJerkMagnitudeMean                            : num  -0.963 -0.992 -0.995 -0.299 -0.295 ...
          TimeBodyGyroscopeJerkMagnitudeStandardDeviation               : num  -0.936 -0.988 -0.995 -0.325 -0.307 ...
          FrequencyuencyBodyAccelerometerMeanXdirection                 : num  -0.9391 -0.9796 -0.9952 -0.2028 0.0382 ...
          FrequencyuencyBodyAccelerometerMeanYdirection                 : num  -0.86707 -0.94408 -0.97707 0.08971 0.00155 ...
          FrequencyuencyBodyAccelerometerMeanZdirection                 : num  -0.883 -0.959 -0.985 -0.332 -0.226 ...
          FrequencyuencyBodyAccelerometerStandardDeviationXdirection    : num  -0.9244 -0.9764 -0.996 -0.3191 0.0243 ...
          FrequencyuencyBodyAccelerometerStandardDeviationYdirection    : num  -0.834 -0.917 -0.972 0.056 -0.113 ...
          FrequencyuencyBodyAccelerometerStandardDeviationZdirection    : num  -0.813 -0.934 -0.978 -0.28 -0.298 ...
          FrequencyuencyBodyAccelerometerMeanFrequencyXdirection        : num  -0.1588 -0.0495 0.0865 -0.2075 -0.3074 ...
          FrequencyuencyBodyAccelerometerMeanFrequencyYdirection        : num  0.0975 0.0759 0.1175 0.1131 0.0632 ...
          FrequencyuencyBodyAccelerometerMeanFrequencyZdirection        : num  0.0894 0.2388 0.2449 0.0497 0.2943 ...
          FrequencyuencyBodyAccelerometerJerkMeanXdirection             : num  -0.9571 -0.9866 -0.9946 -0.1705 -0.0277 ...
          FrequencyuencyBodyAccelerometerJerkMeanYdirection             : num  -0.9225 -0.9816 -0.9854 -0.0352 -0.1287 ...
          FrequencyuencyBodyAccelerometerJerkMeanZdirection             : num  -0.948 -0.986 -0.991 -0.469 -0.288 ...
          FrequencyuencyBodyAccelerometerJerkStandardDeviationXdirection: num  -0.9642 -0.9875 -0.9951 -0.1336 -0.0863 ...
          FrequencyuencyBodyAccelerometerJerkStandardDeviationYdirection: num  -0.932 -0.983 -0.987 0.107 -0.135 ...
          FrequencyuencyBodyAccelerometerJerkStandardDeviationZdirection: num  -0.961 -0.988 -0.992 -0.535 -0.402 ...
          FrequencyuencyBodyAccelerometerJerkMeanFrequencyXdirection    : num  0.132 0.257 0.314 -0.209 -0.253 ...
          FrequencyuencyBodyAccelerometerJerkMeanFrequencyYdirection    : num  0.0245 0.0475 0.0392 -0.3862 -0.3376 ...
          FrequencyuencyBodyAccelerometerJerkMeanFrequencyZdirection    : num  0.02439 0.09239 0.13858 -0.18553 0.00937 ...
          FrequencyuencyBodyGyroscopeMeanXdirection                     : num  -0.85 -0.976 -0.986 -0.339 -0.352 ...
          FrequencyuencyBodyGyroscopeMeanYdirection                     : num  -0.9522 -0.9758 -0.989 -0.1031 -0.0557 ...
          FrequencyuencyBodyGyroscopeMeanZdirection                     : num  -0.9093 -0.9513 -0.9808 -0.2559 -0.0319 ...
          FrequencyuencyBodyGyroscopeStandardDeviationXdirection        : num  -0.882 -0.978 -0.987 -0.517 -0.495 ...
          FrequencyuencyBodyGyroscopeStandardDeviationYdirection        : num  -0.9512 -0.9623 -0.9871 -0.0335 -0.1814 ...
          FrequencyuencyBodyGyroscopeStandardDeviationZdirection        : num  -0.917 -0.944 -0.982 -0.437 -0.238 ...
          FrequencyuencyBodyGyroscopeMeanFrequencyXdirection            : num  -0.00355 0.18915 -0.12029 0.01478 -0.10045 ...
          FrequencyuencyBodyGyroscopeMeanFrequencyYdirection            : num  -0.0915 0.0631 -0.0447 -0.0658 0.0826 ...
          FrequencyuencyBodyGyroscopeMeanFrequencyZdirection            : num  0.010458 -0.029784 0.100608 0.000773 -0.075676 ...
          FrequencyuencyBodyAccelerometerMagnitudeMean                  : num  -0.8618 -0.9478 -0.9854 -0.1286 0.0966 ...
          FrequencyuencyBodyAccelerometerMagnitudeStandardDeviation     : num  -0.798 -0.928 -0.982 -0.398 -0.187 ...
          FrequencyuencyBodyAccelerometerMagnitudeMeanFrequency         : num  0.0864 0.2367 0.2846 0.1906 0.1192 ...
          FrequencyuencyBodyAccelerometerJerkMagnitudeMean              : num  -0.9333 -0.9853 -0.9925 -0.0571 0.0262 ...
          FrequencyuencyBodyAccelerometerJerkMagnitudeStandardDeviation : num  -0.922 -0.982 -0.993 -0.103 -0.104 ...
          FrequencyuencyBodyAccelerometerJerkMagnitudeMeanFrequency     : num  0.2664 0.3519 0.4222 0.0938 0.0765 ...
          FrequencyuencyBodyGyroscopeMagnitudeMean                      : num  -0.862 -0.958 -0.985 -0.199 -0.186 ...
          FrequencyuencyBodyGyroscopeMagnitudeStandardDeviation         : num  -0.824 -0.932 -0.978 -0.321 -0.398 ...
          FrequencyuencyBodyGyroscopeMagnitudeMeanFrequency             : num  -0.139775 -0.000262 -0.028606 0.268844 0.349614 ...
          FrequencyuencyBodyGyroscopeJerkMagnitudeMean                  : num  -0.942 -0.99 -0.995 -0.319 -0.282 ...
          FrequencyuencyBodyGyroscopeJerkMagnitudeStandardDeviation     : num  -0.933 -0.987 -0.995 -0.382 -0.392 ...
          FrequencyuencyBodyGyroscopeJerkMagnitudeMeanFrequency         : num  0.176 0.185 0.334 0.191 0.19 ...